export const RESELLER_REQUEST = "RESELLER_REQUEST"
export const ALL_RESELLER_REQUEST = "ALL_RESELLER_REQUEST"
export const ALL_CUSTOMERS_REQUEST = "ALL_CUSTOMERS_REQUEST"
export const RESELLER_SUCCESS = "RESELLER_SUCCESS"
export const ALL_RESELLER_SUCCESS = "ALL_RESELLER_SUCCESS"
export const ALL_CUSTOMERS_SUCCESS = "ALL_CUSTOMERS_SUCCESS"
export const RESELLER_FAIL = "RESELLER_FAIL"
export const ALL_RESELLER_FAIL = "ALL_RESELLER_FAIL"
export const ALL_CUSTOMERS_FAIL = "ALL_CUSTOMERS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const LOGOUT_RESELLER_SUCCESS = "LOGOUT_RESELLER_SUCCESS"
export const LOGOUT_RESELLER_FAIL = "LOGOUT_RESELLER_FAIL"

export const LOAD_RESELLER_REQUEST = "LOAD_RESELLER_REQUEST"
export const LOAD_RESELLER_SUCCESS = "LOAD_RESELLER_SUCCESS"
export const LOAD_RESELLER_FAIL = "LOAD_RESELLER_FAIL"

export const ADD_RESELLER_SUCCESS = "ADD_RESELLER_SUCCESS"
export const ADD_RESELLER_REQUEST = "ADD_RESELLER_REQUEST"
export const ADD_RESELLER_FAIL = "ADD_RESELLER_FAIL"


export const GET_ALL_RESELLER_REQUEST = "GET_ALL_RESELLER_REQUEST"
export const GET_ALL_RESELLER_SUCCESS = "GET_ALL_RESELLER_SUCCESS"
export const GET_ALL_RESELLER_FAIL = "GET_ALL_RESELLER_FAIL"

